"""Write index.md: links to the docs and every run, with headline held-out metrics."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def title(md):
    return next((line[2:].strip() for line in md.read_text().splitlines() if line.startswith("# ")), md.stem)


def read_json(path):
    return json.loads(path.read_text()) if path.exists() else {}


def run_section(run):
    status = read_json(run / "status.json")
    args = status.get("args", {})
    report = run / "report.md"
    heading = f"[{title(report)}]({report.relative_to(ROOT)})" if report.exists() else "*(no report)*"
    lines = [f"### `{run.name}`", "", heading, ""]
    fmt = lambda v: ", ".join(map(str, v)) if isinstance(v, list) else v
    config = "; ".join(f"{k.replace('_', ' ')}: {fmt(args[k])}" for k in ["train_limit", "eval_limit", "seeds", "modes", "max_steps", "epochs"]
                       if k in args)
    lines.append(f"State: **{status.get('state', 'unknown')}**" + (f" · {config}" if config else ""))
    summary = read_json(run / "summary.json") or read_json(run / "result.json").get("metrics", {})
    if summary and all("fractional" in m for m in summary.values()):
        lines += ["", "Fixed-answer evaluation, fractional readout:", "",
                  "| Checkpoint | ECE ↓ | Brier ↓ | NLL ↓ | AUROC ↑ | Valid mass | Invalid sampled |",
                  "|---|---:|---:|---:|---:|---:|---:|"]
        for name, m in summary.items():
            f = m["fractional"]
            lines.append(f"| {name.removesuffix('-eval')} | {f['ece']:.3f} | {f['brier']:.3f} | {f['nll']:.3f} | "
                         f"{f['auroc']:.3f} | {m['mean_valid_confidence_mass']:.3f} | "
                         f"{m['invalid_confidence_rate']:.1%} |")
        n = next(iter(summary.values()))
        lines += ["", f"{n['total_valid_answers']} held-out answers (accuracy {n['fractional']['accuracy']:.1%})."]
    elif summary:
        lines += ["", "Released evaluation protocol (generated answer + confidence):", "",
                  "| Checkpoint | ECE ↓ | Brier ↓ | AUROC ↑ | Accuracy | Wrong format |",
                  "|---|---:|---:|---:|---:|---:|"]
        for name, m in summary.items():
            lines.append(f"| {name} | {m['ece']:.3f} | {m['brier']:.3f} | {m['auroc']:.3f} | "
                         f"{m['accuracy']:.1%} | {m['wrong_format_rate']:.1%} |")
    return lines + [""]


def main():
    lines = ["# Rewarding Doubt experiments", "",
             "Generated by `scripts/make_index.py`; rerun `scripts/render_reports.sh` to refresh.", "",
             "## Docs", "",
             "- [Project README](README.md): setup, paper-vs-code differences, cost estimates",
             f"- [{title(ROOT / 'docs/objectives.md')}](docs/objectives.md): "
             "formulas, optima and trade-offs of each objective and readout", "",
             "## Runs (newest first)", ""]
    runs = sorted((p for p in (ROOT / "runs").iterdir() if p.is_dir()), key=lambda p: p.name.split("-")[-1],
                  reverse=True)
    for run in runs:
        lines += run_section(run)
    (ROOT / "index.md").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
